package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting amount. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLAmount extends AbstractAmount {

	/** mass, volume */
	public enum Type {
		/** mass */
		MASS,
		/** volume */
		VOLUME;
	}
	
    /**
     * constructor.
     */
    public CMLAmount() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLAmount(CMLAmount old) {
        super((AbstractAmount) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLAmount(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLAmount
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLAmount();

    }


}
