package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting bondType. * autogenerated from schema use as
 * a shell which can be edited
 *
 */
public class CMLBondType extends AbstractBondType {

    /**
     * constructor.
     */
    public CMLBondType() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLBondType(CMLBondType old) {
        super((AbstractBondType) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLBondType(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLBondType
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLBondType();

    }
}
