// /*======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ======*/
package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * An element to hold any combination of heterogeneous element children.
 *
 *
 * complexObject can be used as it stands but will often be extended by\n schema
 * definitions in dictionary entries.
 *
 * user-modifiable class autogenerated from schema if no class exists use as a
 * shell which can be edited the autogeneration software will not overwrite an
 * existing class file
 *
 */
public class CMLComplexObject extends AbstractComplexObject {

    /**
     * must give simple documentation.
     *
     *
     */

    public CMLComplexObject() {
    }

    /**
     * must give simple documentation.
     *
     * @param old
     *            CMLComplexObject to copy
     *
     */

    public CMLComplexObject(CMLComplexObject old) {
        super((AbstractComplexObject) old);
    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLComplexObject(this);
    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLComplexObject
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLComplexObject();
    }
}
