package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting conditionList. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLConditionList extends AbstractConditionList {

    /**
     * constructor.
     */
    public CMLConditionList() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLConditionList(CMLConditionList old) {
        super((AbstractConditionList) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLConditionList(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLConditionList
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLConditionList();

    }
}
