package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLConstants;
import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting identifier. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLIdentifier extends AbstractIdentifier {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLIdentifier() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLIdentifier(CMLConstants old) {
        super((AbstractIdentifier) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLIdentifier(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLIdentifier
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLIdentifier();

    }
}
