package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting object. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLObject extends AbstractObject {

    /**
     * constructor.
     */
    public CMLObject() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLObject(CMLObject old) {
        super((AbstractObject) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLObject(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLObject
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLObject();

    }
}
