package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.attribute.DictRefAttribute;
import org.xmlcml.cml.base.CMLElement;
import org.xmlcml.cml.interfacex.HasDictRef;

/**
 * user-modifiable class supporting parameter. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLParameter extends AbstractParameter implements HasDictRef {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLParameter() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLParameter(CMLParameter old) {
        super((AbstractParameter) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLParameter(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLParameter
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLParameter();

    }
    
        /** null
    	    * @return String
    	    */
    public String getDictRef() {
        DictRefAttribute att = (DictRefAttribute) this.getDictRefAttribute();
        if (att == null) {
            return null;
        }
        return att.getString();
    }
}
