package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting reactionStep. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLReactionStep extends AbstractReactionStep {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLReactionStep() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLReactionStep(CMLReactionStep old) {
        super((AbstractReactionStep) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLReactionStep(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLReactionStep
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLReactionStep();

    }
}
