package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting reactiveCentre. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLReactiveCentre extends AbstractReactiveCentre {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLReactiveCentre() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLReactiveCentre(CMLReactiveCentre old) {
        super((AbstractReactiveCentre) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLReactiveCentre(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLReactiveCentre
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLReactiveCentre();

    }
}
