package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting substance. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLSubstance extends AbstractSubstance {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLSubstance() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLSubstance(CMLSubstance old) {
        super((AbstractSubstance) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLSubstance(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLSubstance
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLSubstance();

    }
}
