package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting substanceList. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLSubstanceList extends AbstractSubstanceList {

    /** */
    public final static String TAG = "substanceList";

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLSubstanceList() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLSubstanceList(CMLSubstanceList old) {
        super((AbstractSubstanceList) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLSubstanceList(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLSubstanceList
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLSubstanceList();

    }
}
