package org.xmlcml.cml.element;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting spectrumList. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLSpectrumList extends AbstractSpectrumList {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLSpectrumList() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLSpectrumList(CMLSpectrumList old) {
        super((AbstractSpectrumList) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLSpectrumList(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLSpectrumList
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLSpectrumList();

    }
}
