package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting actionList. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLActionList extends AbstractActionList {

    /**
     * constructor.
     */
    public CMLActionList() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLActionList(CMLActionList old) {
        super((AbstractActionList) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLActionList(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLActionList
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLActionList();

    }
}
