package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting atomTypeList. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLAtomTypeList extends AbstractAtomTypeList {

    /**
     * constructor.
     */
    public CMLAtomTypeList() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLAtomTypeList(CMLAtomTypeList old) {
        super((AbstractAtomTypeList) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLAtomTypeList(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLAtomTypeList
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLAtomTypeList();

    }
}
