package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting action. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLAction extends AbstractAction {

    /**
     * constructor.
     */
    public CMLAction() {
    }

    /**
     * constructor.
     *
     * @param old
     */

    public CMLAction(CMLAction old) {
        super((AbstractAction) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLAction(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLAction
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLAction();

    }
}
