package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * The abundance of an isotope.
 *
 *
 * The abundance of an isotope in an isotopeList. Values are expressed in
 * percentages. user-modifiable class autogenerated from schema use as a shell
 * which can be edited
 *
 */
public class CMLAbundance extends AbstractAbundance {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLAbundance() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLAbundance(CMLAbundance old) {
        super((AbstractAbundance) old);
    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLAbundance(this);
    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLAbundance
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLAbundance();
    }

    /* ======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ====== */
}
