package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting expression. * autogenerated from schema use
 * as a shell which can be edited
 *
 */
public class CMLExpression extends AbstractExpression {

    /**
     * constructor.
     */
    public CMLExpression() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLExpression(CMLExpression old) {
        super((AbstractExpression) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLExpression(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLExpression
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLExpression();

    }
}
