package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting gradient. * autogenerated from schema use as
 * a shell which can be edited
 *
 */
public class CMLGradient extends AbstractGradient {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLGradient() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLGradient(CMLGradient old) {
        super((AbstractGradient) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLGradient(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLGradient
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLGradient();

    }
}
