package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting isotope. * autogenerated from schema use as
 * a shell which can be edited
 *
 */
public class CMLIsotope extends AbstractIsotope {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLIsotope() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLIsotope(CMLIsotope old) {
        super((AbstractIsotope) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLIsotope(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLIsotope
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLIsotope();

    }
}
