// /*======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ======*/
package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * A kpoint.
 *
 *
 * Not yet finalised.
 *
 * user-modifiable class autogenerated from schema if no class exists use as a
 * shell which can be edited the autogeneration software will not overwrite an
 * existing class file
 *
 */
public class CMLKpoint extends AbstractKpoint {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * must give simple documentation.
     *
     *
     */

    public CMLKpoint() {
    }

    /**
     * must give simple documentation.
     *
     * @param old
     *            CMLKpoint to copy
     *
     */

    public CMLKpoint(CMLKpoint old) {
        super((AbstractKpoint) old);
    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLKpoint(this);
    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLKpoint
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLKpoint();
    }
}
