package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting potentialForm. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLPotentialForm extends AbstractPotentialForm {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLPotentialForm() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLPotentialForm(CMLPotentialForm old) {
        super((AbstractPotentialForm) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLPotentialForm(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLPotentialForm
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLPotentialForm();

    }
}
