package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting reactionScheme. * autogenerated from schema
 * use as a shell which can be edited
 *
 */
public class CMLReactionScheme extends AbstractReactionScheme {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLReactionScheme() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLReactionScheme(CMLReactionScheme old) {
        super((AbstractReactionScheme) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLReactionScheme(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLReactionScheme
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLReactionScheme();

    }
}
