package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting sample. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLSample extends AbstractSample {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLSample() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLSample(CMLSample old) {
        super((AbstractSample) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLSample(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLSample
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLSample();

    }
}
