// /*======AUTOGENERATED FROM SCHEMA; DO NOT EDIT BELOW THIS LINE ======*/
package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/** List of rows in rowBased table.
*
*
* \n Metadata for rows must be defined in tableHeader.\n
*
* user-modifiable class autogenerated from schema if no class exists
* use as a shell which can be edited
* the autogeneration software will not overwrite an existing class file

*/
public class CMLTableRowList extends AbstractTableRowList {

    /** must give simple documentation.
    *

    */

    public CMLTableRowList() {
    }
    /** must give simple documentation.
    *
    * @param old CMLTableRowList to copy

    */

    public CMLTableRowList(CMLTableRowList old) {
        super((org.xmlcml.cml.element.main.AbstractTableRowList) old);
    }

    /** copy node .
    *
    * @return Node
    */
    public Node copy() {
        return new CMLTableRowList(this);
    }
    /** create new instance in context of parent, overridable by subclasses.
    *
    * @param parent parent of element to be constructed (ignored by default)
    * @return CMLTableRowList
    */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLTableRowList();
    }

}
