package org.xmlcml.cml.element.main;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting yaxis. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLYaxis extends AbstractYaxis {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * contructor.
     */
    public CMLYaxis() {
    }

    /**
     * contructor.
     *
     * @param old
     */
    public CMLYaxis(CMLYaxis old) {
        super((AbstractYaxis) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLYaxis(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLYaxis
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLYaxis();

    }
}
