package org.xmlcml.cml.element.lite;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;

/**
 * user-modifiable class supporting name. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLName extends AbstractName {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLName() {
        super();
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLName(CMLName old) {
        super((AbstractName) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLName(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLName
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLName();

    }
}
