package org.xmlcml.cml.element.lite;

import nu.xom.Element;
import nu.xom.Node;

import org.xmlcml.cml.base.CMLElement;
import org.xmlcml.cml.interfacex.PeakOrGroup;

/**
 * user-modifiable class supporting peak. * autogenerated from schema use as a
 * shell which can be edited
 *
 */
public class CMLPeak extends AbstractPeak implements PeakOrGroup {

	/** namespaced element name.*/
	public final static String NS = C_E+TAG;

    /**
     * constructor.
     */
    public CMLPeak() {
    }

    /**
     * constructor.
     *
     * @param old
     */
    public CMLPeak(CMLPeak old) {
        super((AbstractPeak) old);

    }

    /**
     * copy node .
     *
     * @return Node
     */
    public Node copy() {
        return new CMLPeak(this);

    }

    /**
     * create new instance in context of parent, overridable by subclasses.
     *
     * @param parent
     *            parent of element to be constructed (ignored by default)
     * @return CMLPeak
     */
    public CMLElement makeElementInContext(Element parent) {
        return new CMLPeak();

    }
//    OBSOLETE?
//	/** ensure integrity between list and children.
//	 * @return CMLPeakList.class
//	 */
//	public Class getIndexableListClass() {
//		return CMLPeakList.class;
//	}

}
